(() => {
const $=id=>document.getElementById(id), el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};
let listScroll={main:0,top:0,left:0},tabLayoutCleanup=null;
let source=createDataSource();let config,records={contracts:[],cases:[]},kind='contracts',view='全部',filters={},sort={key:'title',direction:1},selected=null,editing=null,returnFocus=null,columnPreferences={},columnDraft={},columnReset=false;try{columnPreferences=ContractTable.readColumns(localStorage)}catch{}
const views=['全部','90 天內到期','自動續約須通知','已逾期','到期日未載明','審閱中'],filterKeys=['department','counterparty_category','contract_type','status','governing_law'];
const columns=['contract_id','title','department','owner','counterparty_name','contract_type','status','end_date','renewal_type','notice_days','contract_value','currency','contract_language','governing_law','dispute_resolution'];
const field=name=>config.schema.fields.find(f=>f.name===name), label=name=>name==='case_number'?'案號':field(name)?.label||name;
function updateMode(){if(source.mode==='demo'){$('mode-notice').hidden=false;$('mode-notice').textContent=source.status();document.querySelector('.help-link').href=location.protocol==='file:'?'../docs-site/site/index.html':'/docs/index.html'}}
function notify(message){$('notice').textContent=message;$('notice').hidden=!message}
function icon(id,name){$(id).innerHTML=window.FluentIcons[name]}
function enumValues(f){const list=config.schema.enums?.[f.enum||f.name]||[];return list.map(v=>typeof v==='string'?v:v.label)}
function matchView(r,v){return ContractTable.matchView(r,v,kind)}
function matches(r,omit){const q=$('search').value.trim().toLocaleLowerCase();return(!q||Object.values(r.fields).some(v=>String(v).toLocaleLowerCase().includes(q))||r.id.toLowerCase().includes(q)||String(r.case_number||'').toLowerCase().includes(q))&&Object.entries(filters).every(([k,v])=>k===omit||(r.fields[k]||'')===v)}
function navButton(text,count,active,action){const b=el('button',undefined,'nav-button');b.type='button';b.setAttribute('aria-pressed',active);b.append(el('span',text),el('span',String(count),'badge'));b.addEventListener('click',action);return b}
function availableColumns(){const keys=columns.filter(k=>field(k));if(kind==='cases'){keys.unshift('case_number');keys.splice(3,0,'stage')}for(const f of config.schema.fields)if(!keys.includes(f.name))keys.push(f.name);return keys}
function visibleColumns(){const available=availableColumns(),defaults=kind==='cases'?['case_number',...columns,'stage']:columns;const keys=ContractTable.visibleColumns(defaults,available,records[kind],columnPreferences[kind]||{});return keys.length?keys:available.slice(0,1)}
function saveColumns(){try{ContractTable.saveColumns(localStorage,columnPreferences)}catch{}}
function columnChooser(){columnReset=false;const list=$('column-list');list.replaceChildren();const shown=visibleColumns();columnDraft=Object.fromEntries(availableColumns().map(key=>[key,shown.includes(key)]));for(const key of availableColumns()){const labelNode=el('label',undefined,'column-option'),input=el('input');input.type='checkbox';input.value=key;input.checked=columnDraft[key];input.addEventListener('change',()=>{columnReset=false;columnDraft[key]=input.checked;$('columns-apply').disabled=!Object.values(columnDraft).some(Boolean)});labelNode.append(input,el('span',key==='stage'?'案件進度':label(key)));list.append(labelNode)}$('columns-apply').disabled=!shown.length}
function render(){
 if(!config)return;
 $('collections').replaceChildren(...[['contracts','合約庫','document'],['cases','案件','case']].map(([k,l,glyph])=>{const button=navButton(l,records[k].length,kind===k,()=>{kind=k;view='全部';filters={};selected=null;closeDrawer();render()});button.classList.add('page-link');const symbol=el('span',undefined,'nav-icon');symbol.innerHTML=FluentIcons[glyph];button.prepend(symbol);if(kind===k)button.setAttribute('aria-current','page');return button}));
 $('views-label').textContent=(kind==='cases'?'案件':'合約庫')+'的檢視';$('filter-count').textContent=Object.keys(filters).length?` · ${Object.keys(filters).length} 個條件`:'';
 $('views').replaceChildren(...views.map(v=>navButton(v,records[kind].filter(r=>matchView(r,v)&&matches(r)).length,view===v,()=>{view=v;render()})));
 const panel=$('filters');panel.replaceChildren();for(const key of filterKeys){if(!field(key))continue;const d=el('details',undefined,'filter-group');d.open=Boolean(filters[key]);d.append(el('summary',key==='department'?'依部門':label(key)));const options=[...new Set(records[kind].map(r=>r.fields[key]||''))].sort((a,b)=>a.localeCompare(b,'zh-Hant'));for(const v of options){const count=records[kind].filter(r=>matchView(r,view)&&matches(r,key)&&(r.fields[key]||'')===v).length;d.append(navButton((key==='department'?v.split('／').at(-1):v)||'未載明',count,filters[key]===v,()=>{if(filters[key]===v)delete filters[key];else filters[key]=v;render()}))}panel.append(d)}
 if(kind==='cases'&&!$('case-page').hidden)return;
 const available=availableColumns(),keys=visibleColumns();$('table').querySelector('colgroup')?.remove();$('table').classList.remove('resizable-table');$('table').style.width='';
 const head=el('tr');for(const key of keys){const th=el('th');th.scope='col';th.setAttribute('aria-sort',sort.key===key?(sort.direction===1?'ascending':'descending'):'none');const b=el('button',key==='stage'?'案件進度':label(key));b.type='button';if(sort.key===key){const span=el('span');span.innerHTML=window.FluentIcons[sort.direction===1?'arrow-up':'arrow-down'];b.append(span)}b.addEventListener('click',()=>{sort={key,direction:sort.key===key?-sort.direction:1};render()});th.append(b);head.append(th)}$('table').tHead.replaceChildren(head);
 const list=records[kind].filter(r=>matchView(r,view)&&matches(r));list.sort((a,b)=>{const av=sort.key==='stage'?a.stage:sort.key==='case_number'?a.case_number||a.id:a.fields[sort.key]||'',bv=sort.key==='stage'?b.stage:sort.key==='case_number'?b.case_number||b.id:b.fields[sort.key]||'';const number=field(sort.key)?.type==='number';return(number?(Number(av)||0)-(Number(bv)||0):String(av).localeCompare(String(bv),'zh-Hant',{numeric:true}))*sort.direction});
 $('table').tBodies[0].replaceChildren();for(const r of list){const tr=el('tr');tr.tabIndex=0;tr.dataset.id=r.id;tr.setAttribute('aria-selected',selected?.id===r.id);tr.setAttribute('aria-label',`${r.fields.title||r.id}，開啟明細`);for(const key of keys){const value=ContractHttp.displayValue(key==='stage'?r.stage:key==='case_number'?r.case_number||r.id:key==='notes'?ContractSources.humanNotes(r.fields[key]):r.fields[key]),td=el('td'),content=el('div',undefined,'cell-content');content.append(el('span',key==='department'?value.split('／').at(-1):value,'cell-value'));markDemo(content,r,key);td.append(content);td.title=value;if(['contract_value','notice_days'].includes(key))td.className='num';tr.append(td)}tr.addEventListener('click',()=>openRecord(r.id,tr));tr.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openRecord(r.id,tr)}});$('table').tBodies[0].append(tr)}if(!list.length){const tr=el('tr'),td=el('td','無符合條件的紀錄','empty');td.colSpan=keys.length;tr.append(td);$('table').tBodies[0].append(tr)}
 ContractColumnResize.attach($('table'),keys,kind,safeStorage);
 $('view-title').textContent=kind==='cases'?'案件':(view==='全部'?'合約庫':view);$('count').textContent=`${list.length} / ${records[kind].length} 筆`;$('table').setAttribute('aria-label',kind==='cases'?'案件清單':'合約主檔');
}
async function reload(){try{[records.contracts,records.cases]=await Promise.all([source.list('contracts'),source.list('cases')]);render();notify('');updateMode()}catch(e){notify(e.message)}}
function closeDrawer(){
 const id=selected?.id,wasCase=!$('case-page').hidden;
 $('drawer').hidden=true;$('case-page').hidden=true;
 document.querySelectorAll('[data-list-view]').forEach(node=>node.hidden=false);
 const header=document.querySelector('.drawer-head'),body=$('detail-body');
 if(header.parentElement!==$('drawer'))$('drawer').append(header,body);
 selected=null;
 if(wasCase)render();
 if(wasCase){$('main').scrollTop=listScroll.main;const wrap=document.querySelector('.tablewrap');wrap.scrollTop=listScroll.top;wrap.scrollLeft=listScroll.left}
 const row=[...$('table').tBodies[0].rows].find(r=>r.dataset.id===id);(row||returnFocus)?.focus({preventScroll:true});
}
function recordWorkspace(){
 const page=$('case-page');
 if(kind==='cases'){
  if(page.hidden)$('main').scrollTop=0
  document.querySelectorAll('[data-list-view]').forEach(node=>node.hidden=true);
  $('drawer').hidden=true;page.hidden=false;
  page.append(document.querySelector('.drawer-head'),$('detail-body'));
  const summary=$('case-summary');summary.replaceChildren();
  for(const [title,value]of [['案件進度',selected.stage],['需求部門',selected.fields.department?.split('／').at(-1)],['法務承辦人',selected.fields.owner]]){const item=el('div');item.append(el('span',title,'muted'),el('strong',ContractHttp.displayValue(value)));summary.append(item)}
  $('close').setAttribute('aria-label','返回案件列表');$('close').title='返回案件列表';
 }else{
  page.hidden=true;document.querySelectorAll('[data-list-view]').forEach(node=>node.hidden=false);
  $('drawer').append(document.querySelector('.drawer-head'),$('detail-body'));$('drawer').hidden=false;
  $('close').setAttribute('aria-label','關閉明細');$('close').title='關閉明細';
 }
}
function section(title){const s=el('section');s.append(el('h3',title));return s}
const safeStorage={getItem:key=>{try{return localStorage.getItem(key)}catch{return null}},setItem:(key,value)=>{try{localStorage.setItem(key,value)}catch{}}};
function markDemo(node,record,key){if(ContractSources.isDemoField(record,key))node.append(el('span','範例','demo-tag'))}
function sourceTable(record){const s=section('欄位出處');s.id='detail-sources';const table=el('table',undefined,'source-table'),head=el('thead'),hr=el('tr');for(const title of ['欄位名稱','原文引句','來源','驗證狀態']){const th=el('th',title);th.scope='col';hr.append(th)}head.append(hr);table.append(head);const body=el('tbody');for(const ref of ContractSources.sourceRows(record,config.schema)){const row=el('tr');row.append(el('td',ref.label),el('td',ref.quote));const td=el('td');if(ref.clauseId&&record.original_clauses?.some(c=>String(c.clause_id)===ref.clauseId)){const a=el('a',ref.source);a.href='#original-clause-'+ref.clauseId;a.addEventListener('click',e=>{e.preventDefault();const target=$('original-clause-'+ref.clauseId);target.scrollIntoView({block:'start',behavior:'instant'});target.focus({preventScroll:true})});td.append(a)}else if(ref.url){const a=el('a',ref.source);a.href=ref.url;a.target='_blank';a.rel='noopener noreferrer';td.append(a)}else td.textContent=ref.source;row.append(td,el('td',ref.status));body.append(row)}table.append(body);if(body.children.length){const wrap=el('div',undefined,'source-wrap');wrap.append(table);s.append(wrap)}else s.append(el('p','未載明'));return s}
function structured(value){if(!value)return '';if(typeof value==='object')return JSON.stringify(value,null,2);try{return JSON.stringify(JSON.parse(value),null,2)}catch{return value}}
async function openRecord(id,origin){try{const previousTab=kind==='cases'&&selected?.id===id?$('detail-body').querySelector('[role=tab][aria-selected=true]')?.id:null;if(kind==='cases'&&$('case-page').hidden){const wrap=document.querySelector('.tablewrap');listScroll={main:$('main').scrollTop,top:wrap.scrollTop,left:wrap.scrollLeft}}selected=await source.read(kind,id);if(origin)returnFocus=origin;render();recordWorkspace();$('detail-id').textContent=kind==='cases'?`案件 ${selected.case_number||selected.id} · ${selected.stage}`:(selected.fields.contract_id||selected.id);$('detail-title').textContent=(selected.example&&!String(selected.fields.title).includes('範例')?'【虛構範例】':'')+ContractHttp.displayValue(selected.fields.title);const body=$('detail-body');tabLayoutCleanup?.();tabLayoutCleanup=null;body.replaceChildren();if(selected.original_status==='pending')body.append(el('p','既有合約登錄範例 · 原檔待上傳，無出處','muted'));
const data=selected.original_clauses?.length?el('details',undefined,'record-fields'):section('欄位');if(selected.original_clauses?.length)data.append(el('summary','合約欄位'));const dl=el('dl');for(const f of config.schema.fields){if(['toc','key_clauses','source_refs'].includes(f.name))continue;const dd=el('dd',ContractHttp.displayValue(f.name==='notes'?ContractSources.humanNotes(selected.fields[f.name]):selected.fields[f.name]));markDemo(dd,selected,f.name);dl.append(el('dt',f.label),dd)}data.append(dl);body.append(data);
 for(const [key,title] of [['toc','章節目錄'],['key_clauses','關鍵條款']]){const s=section(field(key)?.label||title);s.append(el('pre',structured(selected.fields[key])||'未載明'));body.append(s)}
 if(selected.original_status!=='pending')body.append(sourceTable(selected));
 if(selected.original_clauses?.length){const original=section('原文條款');original.id='original-document';for(const clause of selected.original_clauses){const article=el('article',undefined,'original-clause');article.id='original-clause-'+clause.clause_id;article.tabIndex=-1;article.append(el('h3','第 '+clause.clause_id+' 條'+(clause.title?' · '+clause.title:'')),el('p',clause.text));original.append(article)}body.append(original)}
 const timeline=section('處理進度'),ol=el('ol',undefined,'progress');timeline.className='case-timeline';for(const entry of selected.progress||[]){const li=el('li');li.append(el('h3',entry.action+(entry.to_stage&&entry.to_stage!==entry.from_stage?`：${entry.from_stage?entry.from_stage+' → ':''}${entry.to_stage}`:'')),el('p',`${new Date(entry.time).toLocaleString('zh-TW')} · 處理人：${entry.user}`,'meta'),el('p',entry.comment));if(entry.attachment_version)li.append(el('p',`附件版本：${entry.attachment_version}`,'meta'));ol.append(li)}if(!ol.children.length)timeline.append(el('p','尚無進度紀錄','muted'));else timeline.append(ol);if(kind==='cases')body.prepend(timeline);else body.append(timeline);
 if(source.writable&&kind==='cases'){const form=el('form',undefined,'progress-form'),l=el('label','案件狀態'),select=el('select');select.name='stage';for(const stage of [selected.stage,...(config.transitions[selected.stage]||[])]){const o=el('option',stage);o.value=stage;select.append(o)}l.append(select);form.append(l);const hint=el('div',undefined,'approval-hint');const showAuthority=()=>{hint.replaceChildren();hint.hidden=select.value!=='核准';if(!hint.hidden){hint.append(el('h3','核決層級來源提示'));const rules=(config.approvalAuthority?.rules||[]).filter(r=>[r.department,r.department+'部'].includes(String(selected.fields.department||'').split('／').at(-1)));for(const rule of rules){hint.append(el('p',rule.text),el('p',rule.source,'meta'))}hint.append(el('p',config.approvalAuthority?.caveat||'尚未提供核決資料；建議由法務核對公司現行核決辦法。'))}};select.addEventListener('change',showAuthority);showAuthority();form.append(hint);for(const[name,title,textarea]of[['comment','處理意見',true],['attachment_version','附件版本',false]]){const label=el('label',title),input=el(textarea?'textarea':'input');input.name=name;input.required=textarea;label.append(input);form.append(label)}const submit=el('button','保存進度','primary');submit.type='submit';form.append(submit);const err=el('p',undefined,'form-error');err.setAttribute('role','alert');form.append(err);form.addEventListener('submit',async e=>{e.preventDefault();submit.disabled=true;const id=selected.id;try{await source.appendProgress(kind,id,{...Object.fromEntries(new FormData(form)),user:$('user').value,token:selected.token});await reload();await openRecord(id)}catch(error){err.textContent=error.message}finally{submit.disabled=false}});body.prepend(form)}
 if(kind==='cases'&&!source.writable&&selected.stage==='核准'){const hint=el('section',undefined,'approval-hint');hint.append(el('h3','核決層級來源提示'));for(const rule of config.approvalAuthority?.rules||[]){if([rule.department,rule.department+'部'].includes(String(selected.fields.department||'').split('／').at(-1)))hint.append(el('p',rule.text),el('p',rule.source,'meta'))}hint.append(el('p',config.approvalAuthority?.caveat||'尚未提供核決資料。'));body.prepend(hint)}
 if(kind==='cases'){
 const detail=el('div');detail.id='detail-panel';detail.setAttribute('role','tabpanel');detail.setAttribute('aria-labelledby','detail-tab');
 const progress=el('div');progress.id='progress-panel';progress.hidden=true;progress.setAttribute('role','tabpanel');progress.setAttribute('aria-labelledby','progress-tab');
 while(body.firstChild){const node=body.firstChild;(node.matches('.progress-form,.case-timeline,.approval-hint')?progress:detail).append(node)}
 const review=el('div');review.id='review-panel';review.hidden=true;review.setAttribute('role','tabpanel');review.setAttribute('aria-labelledby','review-tab');
 const tabs=el('div',undefined,'detail-tabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','案件工作分頁');let loaded=false;
 const panels=[['detail','明細',detail],['review','Word 審閱',review],['progress','進度紀錄',progress]];
 const choice=el('label','案件分頁','case-tab-choice'),select=el('select');select.setAttribute('aria-label','案件分頁');select.setAttribute('aria-controls','detail-panel review-panel progress-panel');choice.append(select);choice.hidden=true;
 for(const [name,title]of panels){const option=el('option',title);option.value=name;select.append(option)}select.onchange=()=>tabs.querySelector('#'+select.value+'-tab').click();
 for(const [name,title,panel]of panels){
  panel.tabIndex=0;const button=el('button',title);button.type='button';button.id=name+'-tab';button.setAttribute('role','tab');button.setAttribute('aria-controls',panel.id);button.setAttribute('aria-selected',String(name==='detail'));button.tabIndex=name==='detail'?0:-1;
  button.onclick=async()=>{select.value=name;for(const [key,,node]of panels)node.hidden=key!==name;for(const b of tabs.children){b.setAttribute('aria-selected',String(b===button));b.tabIndex=b===button?0:-1}
   if(name==='review'&&!loaded){try{await ContractWordReview.mount(review,source,id,{actor:()=>$('user').value});loaded=true}catch(e){review.textContent=e.message}}};
  button.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const buttons=[...tabs.children],index=buttons.indexOf(button),next=e.key==='Home'?0:e.key==='End'?buttons.length-1:(index+(e.key==='ArrowLeft'?-1:1)+buttons.length)%buttons.length;buttons[next].focus();buttons[next].click()}};tabs.append(button)
 }
 body.append(tabs,choice,detail,review,progress);
 const layoutTabs=()=>{tabs.hidden=false;const narrow=tabs.scrollWidth>tabs.clientWidth+1;tabs.hidden=narrow;choice.hidden=!narrow};
 let lastWidth=0;const observer=new ResizeObserver(([entry])=>{if(Math.abs(entry.contentRect.width-lastWidth)>.5){lastWidth=entry.contentRect.width;layoutTabs()}});observer.observe(body);window.addEventListener('layoutchange',layoutTabs);window.addEventListener('resize',layoutTabs);tabLayoutCleanup=()=>{observer.disconnect();window.removeEventListener('layoutchange',layoutTabs);window.removeEventListener('resize',layoutTabs)};layoutTabs();
 if(previousTab)tabs.querySelector('#'+previousTab)?.click();
 }

 $('close').focus()
 }catch(e){notify(e.message)}}
function writable(){for(const id of ['new-contract','new-case','edit','columns'])$(id).disabled=!source.writable}
function openEditor(record=null,newKind=kind){editing={kind:record?kind:newKind,record,initialFields:{}};const nodes=[];for(const f of config.schema.fields){const wrap=el('div',undefined,'field'+(['toc','key_clauses','source_refs','notes','obligations'].includes(f.name)?' long':'')),l=el('label',f.label+(!record&&ContractHttp.requiredOnCreate(f)?' *':''));l.htmlFor=`f-${f.name}`;let input;if(f.name==='owner'&&config.legalOwners?.length){input=el('select');input.append(el('option',record?'未載明':''));for(const name of [...new Set([...config.legalOwners,record?.fields.owner].filter(Boolean))]){const o=el('option',name);o.value=name;input.append(o)}}else if(f.type==='enum'){input=el('select');input.append(el('option',record?'未載明':''));for(const value of enumValues(f)){const o=el('option',value);o.value=value;input.append(o)}const old=record?.fields[f.name];if(old&&!enumValues(f).includes(old)){const o=el('option',old);o.value=old;input.append(o)}}else if(['toc','key_clauses','source_refs','notes','obligations','payment_terms'].includes(f.name))input=el('textarea');else{input=el('input');input.type=f.type==='date'?'date':['number','integer'].includes(f.type)?'number':'text';if(input.type==='number')input.step=f.type==='integer'?'1':'any'}input.id=`f-${f.name}`;input.name=f.name;input.value=record?.fields[f.name]??'';input.required=!record&&ContractHttp.requiredOnCreate(f);if(record&&!input.value)input.placeholder='未載明';if(f.name==='contract_id'&&!record)input.placeholder='留空由系統自動編號';if(f.name==='updated_at'){input.value=ContractTable.localToday();input.readOnly=true}if(f.name==='contract_id'&&record&&editing.kind==='contracts')input.readOnly=true;editing.initialFields[f.name]=input.value;if(f.name==='source_refs')wrap.hidden=true;wrap.append(l,input);nodes.push(wrap)}for(const[name,title]of[['comment','處理意見'],['attachment_version','附件版本']]){const wrap=el('div',undefined,'field'),l=el('label',title),input=el('input');l.htmlFor=`edit-${name}`;input.id=`edit-${name}`;input.name=`_${name}`;input.required=name==='comment';wrap.append(l,input);nodes.push(wrap)}$('form-fields').replaceChildren(...nodes);$('form-error').textContent='';$('editor-title').textContent=(record?'編輯':'新增')+(editing.kind==='cases'?'案件':'合約');$('editor').showModal()}
$('record-form').addEventListener('submit',async e=>{e.preventDefault();$('save').disabled=true;const values=Object.fromEntries(new FormData(e.currentTarget)),body={fields:{},user:$('user').value,comment:values._comment,attachment_version:values._attachment_version,token:editing.record?.token};body.fields=editing.record?ContractHttp.changedFields(values,editing.initialFields,config.schema):Object.fromEntries(config.schema.fields.map(f=>[f.name,values[f.name]||'']));try{const r=editing.record?await source.update(editing.kind,editing.record.id,body):await source.create(editing.kind,body);kind=editing.kind;if(!editing.record){view='全部';filters={};$('search').value=''}$('editor').close();await reload();await openRecord(r.id)}catch(error){$('form-error').textContent=error.message}finally{$('save').disabled=false}});
for(const id of ['cancel','cancel-top'])$(id).addEventListener('click',()=>$('editor').close());$('edit').addEventListener('click',()=>openEditor(selected));$('new-contract').addEventListener('click',()=>openEditor(null,'contracts'));$('new-case').addEventListener('click',()=>openEditor(null,'cases'));
$('column-widths').addEventListener('click',()=>ContractColumnResize.editor($('table')));
$('columns').addEventListener('click',()=>{columnChooser();$('column-editor').showModal()});$('columns-close').addEventListener('click',()=>$('column-editor').close());$('columns-apply').addEventListener('click',()=>{if(columnReset)delete columnPreferences[kind];else columnPreferences[kind]=columnDraft;saveColumns();render();$('column-editor').close()});$('columns-reset').addEventListener('click',()=>{const saved=columnPreferences[kind];delete columnPreferences[kind];columnChooser();if(saved)columnPreferences[kind]=saved;columnReset=true});
$('case-back').addEventListener('click',closeDrawer);$('close').addEventListener('click',closeDrawer);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('editor').open&&!$('column-editor').open)closeDrawer()});$('reset').addEventListener('click',()=>{filters={};view='全部';$('search').value='';render()});$('search').addEventListener('input',render);$('refresh').addEventListener('click',()=>reload());
(async()=>{try{config=await source.init();if(config.organization?.units?.length){const units=config.organization.units;config.legalOwners=config.legalOwners||[...new Set((config.organization.people||[]).filter(p=>/法務|法律/.test(p.unit||'')).map(p=>p.name))];const enumKey=field('department')?.enum||'department';config.schema.enums[enumKey]=units.map(u=>({label:u.path||u.name}));const old=$('user'),select=el('select');select.id='user';select.setAttribute('aria-label','處理人');select.append(el('option','選擇處理人'));for(const person of config.organization.people||[]){const option=el('option',person.name+' · '+(person.unit||''));option.value=person.name;select.append(option)}old.replaceWith(select)}for(const user of config.users||['法務人員甲','需求部門乙','主管丙']){const option=el('option');option.value=user;$('actors').append(option)}if(config.logo){const image=el('img');image.src=config.logo;image.alt='公司標誌';$('brand').append(image);$('brand').hidden=false}for(const [id,name]of[['refresh','refresh'],['close','close'],['cancel-top','close']])icon(id,name);writable();await reload()}catch(e){writable();notify('如需實際使用，建議由您的 AI 協助設定本機程式。'+e.message)}})()
let calendarDay=ContractTable.localToday();setInterval(()=>{const day=ContractTable.localToday();if(day!==calendarDay){calendarDay=day;if(config)render()}},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&config)render()});
})();
