/* File System Access adapter. Sources: MDN showDirectoryPicker; Chrome File System Access guide. */
(()=>{
 const clone=v=>JSON.parse(JSON.stringify(v));
 function parseMarkdown(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/);if(lines[0]!=='---')throw new Error('缺少 YAML 欄位區');const end=lines.indexOf('---',1);if(end<0)throw new Error('欄位區未結束');const fields={};for(let i=1;i<end;i++){const line=lines[i];if(!line.trim()||line.trimStart().startsWith('#'))continue;if(/^\s/.test(line)||!line.includes(':'))throw new Error('欄位須使用頂層 YAML／單行 JSON');const at=line.indexOf(':'),key=line.slice(0,at).trim();let value=line.slice(at+1).trim();if(Object.hasOwn(fields,key))throw new Error('重複欄位');if(['|','|-','|+','>','>-','>+'].includes(value)){const block=[];while(i+1<end&&(!lines[i+1].trim()||lines[i+1].startsWith('  ')))block.push(lines[++i].slice(2));value=block.join(value[0]==='>'?' ':'\n')}else if(/^["\[{]/.test(value))value=JSON.parse(value);else if(value.startsWith("'")&&value.endsWith("'"))value=value.slice(1,-1).replaceAll("''","'");else if(['null','~'].includes(value))value='';fields[key]=value}const match=text.replace(/^\uFEFF/,'').match(/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/),rawBody=text.replace(/^\uFEFF/,'').slice(match[0].length);return{fields,body:rawBody.trim(),rawBody}}
 const header=fields=>'---\n'+Object.entries(fields).map(([k,v])=>`${k}: ${JSON.stringify(v??'')}`).join('\n')+'\n---\n';
 const markdown=(fields,body='')=>header(fields)+'\n'+body+'\n';
 const eventTime=entries=>new Date(Math.max(Date.now(),(Date.parse(entries?.at(-1)?.time)||0)+1)).toISOString();
 const uid=()=>globalThis.crypto.randomUUID(),safeId=id=>{if(!/^[A-Za-z0-9][A-Za-z0-9_-]{0,100}$/.test(id))throw new Error('編號只可含英數字、連字號及底線');return id};
 async function readFile(handle){const f=await handle.getFile(),text=await f.text();return{text,mtime:f.lastModified,size:f.size,parsed:parseMarkdown(text)}}
 const same=(a,b)=>a&&a.mtime===b.mtime&&a.size===b.size&&a.text===b.text;
 async function writeFile(handle,text,expected){const stream=await handle.createWritable({mode:'exclusive'});try{if(expected&&!same(await readFile(handle),expected))throw new Error('其他人已更新資料；請重新載入');await stream.write(text);await stream.close()}catch(e){try{await stream.abort()}catch{}throw e}}
 function validate(fields,schema,isCase=false){for(const f of schema.fields){const value=String(fields[f.name]??'').trim();if(f.required&&!value&&!(isCase&&f.name==='contract_id'))throw new Error(`請填${f.label}`);if(!value)continue;if(f.type==='date'&&(!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(Date.parse(value))||new Date(value+'T00:00:00Z').toISOString().slice(0,10)!==value))throw new Error(`${f.label}日期不符`);if(['number','integer'].includes(f.type)&&(!Number.isFinite(Number(value))||(f.type==='integer'&&!Number.isInteger(Number(value)))))throw new Error(`${f.label}數值不符`);if(f.type==='enum'){const values=(schema.enums?.[f.enum||f.name]||[]).map(x=>typeof x==='string'?x:x.label);if(!values.includes(value))throw new Error(`${f.label}不在選項內`)}if(f.pattern&&!new RegExp(f.pattern).test(value))throw new Error(`${f.label}格式不符`)}return Object.fromEntries(schema.fields.map(f=>[f.name,String(fields[f.name]??'')]))}
 class SnapshotDataSource{constructor(data){this.data=data;this.writable=false}list(kind){return clone(this.data.records[kind]||[])}read(kind,id){const r=this.list(kind).find(r=>r.id===id);if(!r)throw new Error('找不到紀錄');return{...r,progress:clone(this.data.records.progress[`${kind}:${id}`]||[])}}}
 class DirectoryDataSource{
  constructor(root,config){this.root=root;this.config=config;this.writable=true;this.cache=new Map()}
  async directory(name,create=false){return this.root.getDirectoryHandle(name,{create})}
  async list(kind){const results=[];let directory;try{directory=await this.directory(kind==='contracts'?'md':'cases')}catch(e){if(e.name==='NotFoundError')return [];throw e}let index=0;const children=[];for await(const child of directory.entries())children.push(child);children.sort(([a],[b])=>a.localeCompare(b));for(const [name,handle]of children){if(kind==='contracts'&&handle.kind==='file'&&name.endsWith('.md')){const file=await readFile(handle),fields=file.parsed.fields,id=fields.contract_id||`IMPORT-${String(++index).padStart(4,'0')}`;this.cache.set(`${kind}:${id}`,{handle,file,path:name});results.push({id,fields})}else if(kind==='cases'&&handle.kind==='directory'){results.push(await this.read(kind,name))}}return results}
  async caseFiles(id){const dir=await(await this.directory('cases')).getDirectoryHandle(safeId(id)),handle=await dir.getFileHandle('index.md'),file=await readFile(handle);if(file.parsed.fields.case_id&&file.parsed.fields.case_id!==id)throw new Error('案號與資料夾不符');let log;try{log=await dir.getDirectoryHandle('log')}catch(e){if(e.name!=='NotFoundError')throw e}const entries=[];if(log)for await(const[name,h]of log.entries()){if(h.kind==='file'&&name.endsWith('.md')){const p=(await readFile(h)).parsed;const entry={...p.fields,comment:p.body,file:name};if(!entry.user||!entry.time||!Number.isFinite(Date.parse(entry.time))||!/(Z|[+-]\d{2}:\d{2})$/.test(entry.time)||!this.config.stages.includes(entry.to_stage))throw new Error(`案件 ${id} 進度格式不符`);entries.push(entry)}}entries.sort((a,b)=>Date.parse(a.time)-Date.parse(b.time)||a.file.localeCompare(b.file));let stage='';for(const e of entries){if(!stage&&e.to_stage!=='收件')throw new Error('案件首筆狀態須為收件');if(stage&&e.to_stage!==stage&&!this.config.transitions[stage]?.includes(e.to_stage))throw new Error(`案件 ${id} 進度有衝突，請重新核對來源`);if(e.from_stage!==undefined&&e.from_stage!==stage)throw new Error(`案件 ${id} 有同時更新的進度，請核對`);stage=e.to_stage}return{dir,handle,file,entries,stage:stage||'收件',logVersion:entries.map(e=>e.file).join('|')}}
  async read(kind,id){if(kind==='contracts'){if(!this.cache.has(`${kind}:${id}`))await this.list(kind);const cached=this.cache.get(`${kind}:${id}`);if(!cached)throw new Error('找不到合約');const file=await readFile(cached.handle);this.cache.set(`${kind}:${id}`,{...cached,file});return{id,fields:clone(file.parsed.fields),token:{mtime:file.mtime,text:file.text},progress:[]}}const data=await this.caseFiles(id);this.cache.set(`${kind}:${id}`,data);return{id,fields:data.file.parsed.fields,example:String(data.file.parsed.fields.example)==='true',stage:data.stage,token:{mtime:data.file.mtime,text:data.file.text,logs:data.logVersion},progress:data.entries}}
  async create(kind,body){if(!String(body.user||'').trim())throw new Error('請填處理人');const fields=validate(body.fields,this.config.schema,kind==='cases'),id=kind==='cases'?`CASE-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${uid().slice(0,8)}`:safeId(fields.contract_id);if(kind==='contracts'){const dir=await this.directory('md',true);try{await dir.getFileHandle(id+'.md');throw new Error('合約編號已存在')}catch(e){if(e.name!=='NotFoundError')throw e}const handle=await dir.getFileHandle(id+'.md',{create:true});await writeFile(handle,markdown(fields));await this.list(kind)}else{const dir=await(await this.directory('cases',true)).getDirectoryHandle(id,{create:true});await writeFile(await dir.getFileHandle('index.md',{create:true}),markdown({...fields,case_id:id}));await this.writeLog(dir,{time:new Date().toISOString(),user:body.user,action:'新增案件',from_stage:'',to_stage:'收件',attachment_version:body.attachment_version||''},body.comment||'建立案件。')}return this.read(kind,id)}
  async check(kind,id,token){const current=await this.read(kind,id);if(!token||current.token.mtime!==token.mtime||current.token.text!==token.text||(kind==='cases'&&current.token.logs!==token.logs))throw new Error('其他人已更新資料；請重新載入，不會覆蓋。');return current}
  async update(kind,id,body){if(!String(body.user||'').trim())throw new Error('請填處理人');const fields=validate(body.fields,this.config.schema,kind==='cases'),current=await this.check(kind,id,body.token),cached=this.cache.get(`${kind}:${id}`),again=await readFile(cached.handle);if(!same(again,cached.file))throw new Error('其他人已更新資料；請重新載入');const meta={...again.parsed.fields,...fields};if(kind==='contracts')meta.contract_id=current.fields.contract_id;else meta.case_id=id;await writeFile(cached.handle,header({...meta,updated_by:body.user})+again.parsed.rawBody,again);if(kind==='cases')await this.writeLog(cached.dir,{time:eventTime(current.progress),user:body.user,action:'更新欄位',from_stage:current.stage,to_stage:current.stage,attachment_version:body.attachment_version||''},body.comment||'更新欄位。');return this.read(kind,id)}
  async writeLog(dir,entry,comment){const log=await dir.getDirectoryHandle('log',{create:true}),name=`${entry.time.replaceAll(':','-')}-${String(entry.user).replace(/[^\p{L}\p{N}_-]/gu,'_').slice(0,24)}-${uid()}.md`;try{await log.getFileHandle(name);throw new Error('紀錄檔已存在')}catch(e){if(e.name!=='NotFoundError')throw e}await writeFile(await log.getFileHandle(name,{create:true}),markdown(entry,comment));return name}
  async appendProgress(kind,id,body){if(kind!=='cases')throw new Error('進度只供案件使用');if(!String(body.user||'').trim()||!String(body.comment||'').trim())throw new Error('請填處理人與意見');const current=await this.check(kind,id,body.token),stage=body.stage||current.stage;if(stage!==current.stage&&!this.config.transitions[current.stage]?.includes(stage))throw new Error('不允許的狀態轉換');await this.writeLog(this.cache.get(`${kind}:${id}`).dir,{time:eventTime(current.progress),user:body.user,action:stage===current.stage?'加入意見':'狀態變更',from_stage:current.stage,to_stage:stage,attachment_version:body.attachment_version||''},body.comment);return this.read(kind,id)}
 }
 async function handleStorage(value,write=false){try{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('contract-folder',1);r.onupgradeneeded=()=>r.result.createObjectStore('handles');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return await new Promise((resolve,reject)=>{const tx=db.transaction('handles',write?'readwrite':'readonly'),store=tx.objectStore('handles'),r=write?store.put(value,'root'):store.get('root');r.onsuccess=()=>{const result=r.result;tx.oncomplete=()=>{db.close();resolve(result)}};r.onerror=()=>{db.close();reject(r.error)}})}catch{return null}}
 window.ContractFiles={parseMarkdown,markdown,validate,SnapshotDataSource,DirectoryDataSource,handleStorage};window.createDataSource=()=>new SnapshotDataSource(window.CONTRACT_DATA);
})();
