/* Append-only review files; same format for people and AI. */
(() => {
  const {DirectoryDataSource,SnapshotDataSource,parseMarkdown,markdown}=ContractFiles;
  function validateReview(data){
    const ids=new Set();for(const v of data.versions){if(!v.version_id||ids.has(v.version_id)||!Array.isArray(v.clauses))throw new Error('審閱版本格式或編號不符');ids.add(v.version_id);const clauses=new Set();for(const c of v.clauses){if(!c.id||clauses.has(c.id)||typeof c.text!=='string')throw new Error('條號須唯一，條款須為文字');clauses.add(c.id)}}
    const events=new Set(),roots=new Map();for(const e of data.comments){if(!e.id||events.has(e.id)||!e.thread_id||!e.user||!Number.isFinite(Date.parse(e.time))||!/(Z|[+-]\d{2}:\d{2})$/.test(e.time)||!['comment','resolve','reopen'].includes(e.action))throw new Error('審閱留言格式不符');events.add(e.id);const v=data.versions.find(v=>v.version_id===e.version_id),c=v?.clauses.find(c=>c.id===e.clause_id);if(!c||e.selector?.type!=='TextQuoteSelector'||!c.text.includes(e.selector.exact)||!e.selector.exact)throw new Error('審閱原文錨點不符');if(!roots.has(e.thread_id)){if(e.action!=='comment'||e.id!==e.thread_id)throw new Error('留言串缺少首筆留言');roots.set(e.thread_id,e)}else{const root=roots.get(e.thread_id);if(root.clause_id!==e.clause_id||root.version_id!==e.version_id||JSON.stringify(root.selector)!==JSON.stringify(e.selector))throw new Error('留言串錨點不可改動')}if(e.action==='comment'&&!String(e.comment||'').trim())throw new Error('留言不可空白')}
    return data;
  }
  SnapshotDataSource.prototype.readReview=function(id){return validateReview(JSON.parse(JSON.stringify(this.data.records.review?.[id]||{versions:[],comments:[]})))};
  DirectoryDataSource.prototype.readReview=async function(id){const data={versions:[],comments:[]},caseData=await this.caseFiles(id);let review;try{review=await caseData.dir.getDirectoryHandle('review')}catch(e){if(e.name==='NotFoundError')return data;throw e}
    for(const name of ['versions','comments']){let dir;try{dir=await review.getDirectoryHandle(name)}catch(e){if(e.name==='NotFoundError')continue;throw e}for await(const[file,h]of dir.entries()){if(h.kind!=='file'||!file.endsWith('.md'))continue;const f=await h.getFile(),p=parseMarkdown(await f.text());data[name].push({...p.fields,...(name==='comments'?{comment:p.body}:{}),file})}}
    data.versions.sort((a,b)=>String(a.version_id).localeCompare(String(b.version_id),undefined,{numeric:true}));data.comments.sort((a,b)=>Date.parse(a.time)-Date.parse(b.time)||a.file.localeCompare(b.file));return validateReview(data);
  };
  DirectoryDataSource.prototype.appendReview=async function(id,body){
    if(!String(body.user||'').trim())throw new Error('請選處理人');const data=await this.readReview(id);if(data.versions.at(-1)?.version_id!==body.expectedVersion)throw new Error('條款版本已更新；請重新載入本輪版本');const entry={id:crypto.randomUUID(),thread_id:body.thread_id||'',clause_id:body.clause_id,version_id:body.version_id,selector:body.selector,user:body.user,time:new Date(Math.max(Date.now(),(Date.parse(data.comments.at(-1)?.time)||0)+1)).toISOString(),action:body.action||'comment',comment:body.comment||''};if(!entry.thread_id)entry.thread_id=entry.id;validateReview({versions:data.versions,comments:[...data.comments,entry]});const caseData=await this.caseFiles(id),review=await caseData.dir.getDirectoryHandle('review',{create:true}),dir=await review.getDirectoryHandle('comments',{create:true}),name=entry.time.replaceAll(':','-')+'-'+entry.id+'.md';
    try{await dir.getFileHandle(name);throw new Error('留言檔已存在')}catch(e){if(e.name!=='NotFoundError')throw e}const latest=await this.readReview(id);if(latest.versions.at(-1)?.version_id!==body.expectedVersion)throw new Error('條款版本已更新，請重新載入');const handle=await dir.getFileHandle(name,{create:true}),stream=await handle.createWritable({mode:'exclusive'});try{const {comment,...meta}=entry;await stream.write(markdown(meta,comment));await stream.close()}catch(e){try{await stream.abort()}catch{}throw e}return this.readReview(id);
  };
  ContractFiles.validateReview=validateReview;
})();
