/* Native Word review, OOXML DOM + MIT fflate. Editing remains in Word. */
(()=>{
 const W='http://schemas.openxmlformats.org/wordprocessingml/2006/main',W14='http://schemas.microsoft.com/office/word/2010/wordml',W15='http://schemas.microsoft.com/office/word/2012/wordml',R='http://schemas.openxmlformats.org/package/2006/relationships',CT='http://schemas.openxmlformats.org/package/2006/content-types';
 const nodes=(root,ns,name)=>[...root.getElementsByTagNameNS(ns,name)],attr=(n,name)=>n.getAttributeNS(W,name)||'',text=n=>[...n.getElementsByTagName('*')].filter(e=>e.namespaceURI===W&&['t','delText'].includes(e.localName)).map(e=>e.textContent).join(''),xml=bytes=>{const d=new DOMParser().parseFromString(fflate.strFromU8(bytes),'application/xml');if(d.getElementsByTagName('parsererror').length)throw Error('Word XML 格式無法讀取');return d};
 const serialize=d=>fflate.strToU8(new XMLSerializer().serializeToString(d));
 function packageData(raw){if(raw.length>10*1024*1024)throw Error('Word 檔案須小於 10 MB');
  // Inspect declared sizes before unzipping; the input comes from an explicitly selected file.
  let size=0;const parts=fflate.unzipSync(raw,{filter:f=>{size+=f.originalSize;if(size>50*1024*1024)throw Error('Word 解壓內容過大');return true}});if(!parts['word/document.xml'])throw Error('不是可讀取的 Word 文件');return parts}
 function heading(value){return value.match(/^\s*第\s*([0-9一二三四五六七八九十百零〇]+)\s*條(?:\s|[：:、.．]|$)(.*)/)}
 function inspect(raw){const parts=packageData(raw),d=xml(parts['word/document.xml']),comments=new Map(),done=new Map();
  if(parts['word/commentsExtended.xml'])for(const e of nodes(xml(parts['word/commentsExtended.xml']),W15,'commentEx'))done.set(e.getAttributeNS(W15,'paraId'),['1','true'].includes(e.getAttributeNS(W15,'done')));
  if(parts['word/comments.xml'])for(const c of nodes(xml(parts['word/comments.xml']),W,'comment')){const p=nodes(c,W,'p')[0];comments.set(attr(c,'id'),{id:'comment-'+attr(c,'id'),type:'comment',author:attr(c,'author')||'未載明',time:attr(c,'date'),content:text(c),quote:'',clause_id:'未載明',resolved:done.get(p?.getAttributeNS(W14,'paraId'))||false})}
  const items=[],clauses=[],active=new Map(),seen=new Set();let current='未載明';
  for(const p of nodes(nodes(d,W,'body')[0],W,'p')){const value=[...p.getElementsByTagName('*')].filter(n=>n.namespaceURI===W&&n.localName==='t'&&!hasAncestor(n,'del')).map(n=>n.textContent).join(''),h=heading(value);if(h){current=h[1];if(seen.has(current))throw Error('條號重複，建議核對文件章節後匯入');seen.add(current);clauses.push({id:current,title:h[2].trim(),text:''})}else if(clauses.length)clauses.at(-1).text+=(clauses.at(-1).text?'\n':'')+value;
   for(const n of p.getElementsByTagName('*')){if(n.namespaceURI!==W)continue;const key=attr(n,'id');if(n.localName==='commentRangeStart'){active.set(key,[]);if(comments.has(key))comments.get(key).clause_id=current}else if(n.localName==='commentRangeEnd'){if(active.has(key)&&comments.has(key)){comments.get(key).quote=active.get(key).join('');active.delete(key)}}else if(['t','delText'].includes(n.localName)){for(const a of active.values())a.push(n.textContent)}else if(['ins','del'].includes(n.localName))items.push({id:(n.localName==='ins'?'insert-':'delete-')+(key||items.length),type:n.localName==='ins'?'insert':'delete',clause_id:current,author:attr(n,'author')||'未載明',time:attr(n,'date'),quote:text(n),content:text(n),resolved:false})}
  }
  for(const[key,a]of active)if(comments.has(key))comments.get(key).quote=a.join('');items.push(...comments.values());return {clauses,word_items:items,unresolved:items.filter(i=>!i.resolved).length}
 }
 function hasAncestor(n,name){for(let a=n.parentNode;a;a=a.parentNode)if(a.namespaceURI===W&&a.localName===name)return true;return false}
 function suggest(raw,suggestions,author='AI'){if(!Array.isArray(suggestions)||!suggestions.length)throw Error('建議須為非空陣列');const parts=packageData(raw),d=xml(parts['word/document.xml']),c=parts['word/comments.xml']?xml(parts['word/comments.xml']):new DOMParser().parseFromString(`<w:comments xmlns:w="${W}"/>`,'application/xml');let next=Math.max(-1,...[...d.getElementsByTagName('*'),...c.getElementsByTagName('*')].map(n=>attr(n,'id')).filter(x=>/^\d+$/.test(x)).map(Number))+1;const now=new Date().toISOString();let current='未載明';const paragraphs=[];
  for(const p of nodes(nodes(d,W,'body')[0],W,'p')){const h=heading(text(p));if(h)current=h[1];else paragraphs.push([current,p])}
  const make=(doc,name)=>doc.createElementNS(W,'w:'+name),run=(value,props,deleted=false)=>{const r=make(d,'r');if(props)r.append(props.cloneNode(true));const t=make(d,deleted?'delText':'t');t.setAttributeNS('http://www.w3.org/XML/1998/namespace','xml:space','preserve');t.textContent=value;r.append(t);return r};
  for(const s of suggestions){if(!s.quote||typeof s.quote!=='string'||!['comment','replace'].includes(s.type))throw Error('建議須有條號、唯一原文及 comment／replace 類型');const matches=[];for(const[cid,p]of paragraphs){if(cid!==String(s.clause_id))continue;for(const r of [...p.children].filter(n=>n.namespaceURI===W&&n.localName==='r')){const ts=[...r.children].filter(n=>n.localName==='t');if(ts.length===1&&[...r.children].every(n=>['rPr','t'].includes(n.localName))&&ts[0].textContent.includes(s.quote)){const value=ts[0].textContent;if(value.split(s.quote).length!==2)throw Error('原文重複，建議縮小文字範圍');matches.push([p,r,value])}}}if(matches.length!==1)throw Error('找不到唯一的單一文字區段；跨格式或修訂範圍建議由 Word 處理');const[p,r,value]=matches[0],props=[...r.children].find(n=>n.localName==='rPr'),at=value.indexOf(s.quote),a=value.slice(0,at),b=value.slice(at+s.quote.length),replacement=[];if(a)replacement.push(run(a,props));
   if(s.type==='comment'){if(typeof s.content!=='string'||!s.content.trim())throw Error('註解內容不可空白');const start=make(d,'commentRangeStart');start.setAttributeNS(W,'w:id',String(next));const end=make(d,'commentRangeEnd');end.setAttributeNS(W,'w:id',String(next));const ref=make(d,'r'),cr=make(d,'commentReference');cr.setAttributeNS(W,'w:id',String(next));ref.append(cr);replacement.push(start,run(s.quote,props),end,ref);const cm=make(c,'comment');for(const[k,v]of Object.entries({id:String(next),author,date:now}))cm.setAttributeNS(W,'w:'+k,v);const cp=make(c,'p');cp.append(c.importNode(run(s.content),true));cm.append(cp);c.documentElement.append(cm);next++}else{if(typeof s.replacement!=='string')throw Error('replacement 須為文字');for(const[tag,value]of[['del',s.quote],['ins',s.replacement]]){if(!value)continue;const n=make(d,tag);for(const[k,v]of Object.entries({id:String(next++),author,date:now}))n.setAttributeNS(W,'w:'+k,v);n.append(run(value,props,tag==='del'));replacement.push(n)}}if(b)replacement.push(run(b,props));r.replaceWith(...replacement)
  }
  parts['word/document.xml']=serialize(d);if(nodes(c,W,'comment').length){parts['word/comments.xml']=serialize(c);const path='word/_rels/document.xml.rels',rels=parts[path]?xml(parts[path]):new DOMParser().parseFromString(`<Relationships xmlns="${R}"/>`,'application/xml');if(!nodes(rels,R,'Relationship').some(n=>n.getAttribute('Type')?.endsWith('/comments'))){const n=rels.createElementNS(R,'Relationship');n.setAttribute('Id','rIdComments'+crypto.randomUUID().replaceAll('-',''));n.setAttribute('Type','http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments');n.setAttribute('Target','comments.xml');rels.documentElement.append(n)}parts[path]=serialize(rels);const ct=xml(parts['[Content_Types].xml']);if(!nodes(ct,CT,'Override').some(n=>n.getAttribute('PartName')==='/word/comments.xml')){const n=ct.createElementNS(CT,'Override');n.setAttribute('PartName','/word/comments.xml');n.setAttribute('ContentType','application/vnd.openxmlformats-officedocument.wordprocessingml.comments+xml');ct.documentElement.append(n)}parts['[Content_Types].xml']=serialize(ct)}return fflate.zipSync(parts)
 }
 const encode=raw=>{let s='';for(let i=0;i<raw.length;i+=32768)s+=String.fromCharCode(...raw.subarray(i,i+32768));return btoa(s)},decode=value=>Uint8Array.from(atob(value),x=>x.charCodeAt(0));
 function record(raw,caseId,filename,user){const result={id:crypto.randomUUID(),case_id:caseId,version_id:'WORD-'+crypto.randomUUID().slice(0,8),format:'docx',filename,user,time:new Date().toISOString(),document_base64:encode(raw),...inspect(raw)};if(new TextEncoder().encode(JSON.stringify(result)).length>9*1024*1024)throw Error('Word 與總覽資料超過本機介面可保存大小，建議由 AI 拆分文件');return result}
 const el=(tag,value,cls)=>{const n=document.createElement(tag);if(value!==undefined)n.textContent=value;if(cls)n.className=cls;return n};
 async function mount(container,source,id,options){let data=await source.readReview(id),versions=data.versions.filter(v=>v.format==='docx').sort((a,b)=>Date.parse(a.time)-Date.parse(b.time)),selected=versions.at(-1),unresolved=false;
  const error=el('p',undefined,'form-error');error.setAttribute('role','alert');
  const save=async(raw,name)=>{const user=options.actor()?.trim();if(!user||user==='選擇處理人')throw Error('請選擇處理人');const r=record(raw,id,name,user);await source.api('review_versions','POST',r);versions.push(r);selected=r;render()};
  function render(){container.replaceChildren();container.append(el('h3','Word 修訂與註解總覽'));const bar=el('div',undefined,'review-toolbar');const label=el('label','Word 版本'),select=el('select');select.setAttribute('aria-label','Word 版本');for(const v of versions){const o=el('option',v.filename+' · '+v.user);o.value=v.id;select.append(o)}select.value=selected?.id||'';select.onchange=()=>{selected=versions.find(v=>v.id===select.value);render()};label.append(select);bar.append(label);const filter=el('label',undefined,'check-label'),check=el('input');check.type='checkbox';check.checked=unresolved;check.onchange=()=>{unresolved=check.checked;render()};filter.append(check,document.createTextNode('只看未解決'));bar.append(filter);
   if(source.writable){const upload=el('div',undefined,'word-upload'),input=el('input'),button=el('button','匯入 Word 修訂稿');button.type='button';input.type='file';input.accept='.docx';input.hidden=true;button.onclick=()=>input.click();upload.append(button);input.setAttribute('aria-label','匯入 Word 修訂稿');input.onchange=async()=>{error.textContent='';try{const f=input.files[0];if(f)await save(new Uint8Array(await f.arrayBuffer()),f.name)}catch(e){error.textContent=e.message}};upload.append(input);bar.append(upload)}container.append(bar,error);
   if(!selected){container.append(el('p','如您方便，可匯入帶修訂與註解的 Word 文件。編輯仍在 Word 進行。'));return}
   const download=el('button','下載此 Word 版本');download.type='button';download.onclick=()=>{const raw=decode(selected.document_base64),url=URL.createObjectURL(new Blob([raw],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'})),a=el('a');a.href=url;a.download=selected.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};container.append(download);
   if(versions.length>1){const comparison=el('details',undefined,'word-comparison');comparison.append(el('summary','逐條版本比對'));const controls=el('div',undefined,'review-toolbar'),before=el('select'),after=el('select');before.setAttribute('aria-label','比較舊版本');after.setAttribute('aria-label','比較新版本');for(const v of versions){for(const select of [before,after]){const o=el('option',v.filename+' · '+v.version_id);o.value=v.id;select.append(o)}}before.value=versions.at(-2).id;after.value=selected.id;const left=el('label','舊版本'),right=el('label','新版本');left.append(before);right.append(after);controls.append(left,right);const content=el('div');comparison.append(controls,content);const draw=()=>{content.replaceChildren();const old=versions.find(v=>v.id===before.value),now=versions.find(v=>v.id===after.value),ids=[...new Set([...(old?.clauses||[]),...(now?.clauses||[])].map(c=>c.id))];for(const cid of ids){const a=old?.clauses.find(c=>c.id===cid),b=now?.clauses.find(c=>c.id===cid),article=el('section',undefined,'review-clause');article.append(el('h4','第 '+cid+' 條'));const text=el('p',undefined,'clause-diff');for(const part of ContractReview.diff(a?.text||'',b?.text||''))text.append(el(part.type==='insert'?'ins':part.type==='delete'?'del':'span',part.text));article.append(text);content.append(article)}};before.onchange=draw;after.onchange=draw;draw();container.append(comparison)}
   const items=(selected.word_items||[]).filter(i=>!unresolved||!i.resolved),ids=[...new Set(items.map(i=>i.clause_id))].sort((a,b)=>{const order=new Map((selected.clauses||[]).map((c,i)=>[c.id,i]));return (order.get(a)??Infinity)-(order.get(b)??Infinity)});for(const cid of ids){const card=el('section',undefined,'review-clause');card.append(el('h3',cid==='未載明'?'條號未載明':'第 '+cid+' 條'));const table=el('table',undefined,'word-summary'),head=el('tr');for(const h of ['類型／狀態','處理人／時間','文字','內容'])head.append(el('th',h));const thead=el('thead');thead.append(head);table.append(thead);const body=el('tbody');for(const item of items.filter(i=>i.clause_id===cid)){const tr=el('tr'),type={comment:'註解',insert:'新增',delete:'刪除'}[item.type],first=el('td',type+' · '+(item.resolved?'已解決':'待處理'));tr.append(first,el('td',item.author+(item.time?'\n'+new Date(item.time).toLocaleString('zh-TW'):'')));const quote=el('td');quote.append(el(item.type==='delete'?'del':item.type==='insert'?'ins':'span',item.quote||'未載明'));tr.append(quote,el('td',item.type==='comment'?item.content:'Word 修訂'));body.append(tr)}table.append(body);const wrap=el('div',undefined,'source-wrap');wrap.append(table);card.append(wrap);container.append(card)}if(!items.length)container.append(el('p','沒有符合條件的 Word 修訂或註解。'));
   if(source.writable){const proposal=el('div',undefined,'word-upload'),input=el('input'),button=el('button','匯入 AI 建議，產生新 Word 版本');button.type='button';input.type='file';input.accept='.json';input.hidden=true;button.onclick=()=>input.click();proposal.append(button);input.setAttribute('aria-label','匯入 AI 建議 JSON');input.onchange=async()=>{error.textContent='';try{const f=input.files[0];if(f){const values=JSON.parse(await f.text()),raw=suggest(decode(selected.document_base64),values,'AI（Codex／Claude）');await save(raw,selected.filename.replace(/\.docx$/i,'-AI建議.docx'))}}catch(e){error.textContent=e.message}};proposal.append(input);container.append(proposal)}
  }render()
 }
 window.ContractWordReview={inspect,suggest,record,mount,encode,decode};
})();
