const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{webcrypto}=require('node:crypto');global.window=global;global.crypto=webcrypto;vm.runInThisContext(fs.readFileSync(__dirname+'/app/datasource.js','utf8'));
vm.runInThisContext(fs.readFileSync(__dirname+'/app/review-data.js','utf8'));vm.runInThisContext(fs.readFileSync(__dirname+'/app/review.js','utf8'));
const {DirectoryDataSource,parseMarkdown,markdown,validate}=ContractFiles;let tick=1000;
const missing=()=>Object.assign(new Error('missing'),{name:'NotFoundError'});
class FileHandle{constructor(name,text=''){this.name=name;this.kind='file';this.text=text;this.mtime=++tick;this.denied=false}async getFile(){return{lastModified:this.mtime,size:Buffer.byteLength(this.text),text:async()=>this.text}}async createWritable(){if(this.denied)throw Object.assign(new Error('denied'),{name:'NotAllowedError'});let pending='';return{write:async text=>{pending=text},close:async()=>{this.text=pending;this.mtime=++tick},abort:async()=>{}}}}
class Directory{constructor(name='root'){this.kind='directory';this.name=name;this.items=new Map()}async getDirectoryHandle(name,{create=false}={}){if(!this.items.has(name)){if(!create)throw missing();this.items.set(name,new Directory(name))}const v=this.items.get(name);if(v.kind!=='directory')throw Error('type');return v}async getFileHandle(name,{create=false}={}){if(!this.items.has(name)){if(!create)throw missing();this.items.set(name,new FileHandle(name))}const v=this.items.get(name);if(v.kind!=='file')throw Error('type');return v}async*entries(){yield*this.items.entries()}}
const config={schema:{fields:[{name:'contract_id',label:'編號',required:true,type:'string'},{name:'title',label:'名稱',required:true,type:'string'},{name:'date',label:'日期',type:'date'},{name:'amount',label:'金額',type:'number'},{name:'status',label:'狀態',type:'enum'}],enums:{status:[{label:'有效'},{label:'審閱中'}]}},stages:['收件','法務審閱','退回需求部門','與對方協商','核准','簽署','歸檔'],transitions:{'收件':['法務審閱'],'法務審閱':['退回需求部門','與對方協商','核准'],'退回需求部門':['法務審閱'],'與對方協商':['法務審閱'],'核准':['簽署'],'簽署':['歸檔'],'歸檔':[]}};
let count=0;const test=async(name,fn)=>{await fn();count++;console.log('PASS '+name)};
(async()=>{const root=new Directory(),source=new DirectoryDataSource(root,config),fields={contract_id:'C-2026-0001',title:'合約',date:'2026-10-07',amount:'10',status:'有效'};let contract,record;
await test('Markdown round trip preserves source text',()=>{const text=markdown({title:'</script>中文',notes:'a\nb'},'原文');assert.equal(parseMarkdown(text).fields.notes,'a\nb');assert.equal(parseMarkdown(text).body,'原文')});
await test('Required, date, number, enum validation',()=>{for(const change of [{title:''},{date:'2026-02-30'},{amount:'bad'},{status:'不存在'}])assert.throws(()=>validate({...fields,...change},config.schema));assert.doesNotThrow(()=>validate({...fields,contract_id:''},config.schema,true))});
await test('Create contract and read',async()=>{contract=await source.create('contracts',{fields,user:'甲'});assert.equal(contract.fields.title,'合約');assert.equal((await source.list('contracts')).length,1)});
await test('Duplicate contract rejected without overwrite',async()=>{await assert.rejects(source.create('contracts',{fields,user:'乙'}),/已存在/);assert.equal((await source.read('contracts',contract.id)).fields.title,'合約')});
await test('Update contract persists handler and fields',async()=>{const updated=await source.update('contracts',contract.id,{fields:{...fields,title:'修改'},user:'甲',token:contract.token});assert.equal(updated.fields.title,'修改');assert.equal(updated.fields.updated_by,'甲');contract=updated});
await test('Updating fields preserves Markdown body exactly',async()=>{const h=source.cache.get('contracts:'+contract.id).handle;h.text=markdown(contract.fields)+'  原文縮排\r\n第二行\r\n';h.mtime++;const current=await source.read('contracts',contract.id),old=parseMarkdown(h.text).rawBody;contract=await source.update('contracts',contract.id,{fields:{...fields,title:'保留原文'},user:'甲',token:current.token});assert.equal(parseMarkdown(h.text).rawBody,old)});
await test('Stale mtime conflict does not overwrite',async()=>{const handle=source.cache.get('contracts:'+contract.id).handle;handle.text=markdown({...fields,title:'同事更新'});handle.mtime++;await assert.rejects(source.update('contracts',contract.id,{fields,user:'甲',token:contract.token}),/其他人/);assert.equal(parseMarkdown(handle.text).fields.title,'同事更新')});
await test('Same timestamp content conflict detected',async()=>{const current=await source.read('contracts',contract.id),handle=source.cache.get('contracts:'+contract.id).handle;handle.text=markdown({...fields,title:'不同內容'});await assert.rejects(source.update('contracts',contract.id,{fields,user:'甲',token:current.token}),/其他人/)});
await test('Permission loss keeps source unchanged',async()=>{const current=await source.read('contracts',contract.id),handle=source.cache.get('contracts:'+contract.id).handle,old=handle.text;handle.denied=true;await assert.rejects(source.update('contracts',contract.id,{fields,user:'甲',token:current.token}),/denied/);assert.equal(handle.text,old);handle.denied=false});
await test('Auto case ID, initial progress and actor',async()=>{record=await source.create('cases',{fields:{...fields,contract_id:''},user:'需求人甲',comment:'收到附件',attachment_version:'V1'});assert.match(record.id,/^CASE-\d{8}-/);assert.equal(record.stage,'收件');assert.equal(record.progress[0].user,'需求人甲')});
await test('Progress creates one new file, old files unchanged',async()=>{const log=await(await(await root.getDirectoryHandle('cases')).getDirectoryHandle(record.id)).getDirectoryHandle('log'),old=[...log.items.values()].map(f=>f.text);record=await source.appendProgress('cases',record.id,{stage:'法務審閱',user:'法務乙',comment:'開始審閱',attachment_version:'V2',token:record.token});assert.equal(log.items.size,2);assert.equal([...log.items.values()][0].text,old[0]);assert.equal(record.progress.at(-1).attachment_version,'V2')});
await test('Multiple negotiation rounds retained',async()=>{for(const stage of ['與對方協商','法務審閱','退回需求部門','法務審閱','核准','簽署','歸檔'])record=await source.appendProgress('cases',record.id,{stage,user:'法務乙',comment:'意見',token:record.token});assert.equal(record.stage,'歸檔');assert.equal(record.progress.length,9)});
await test('Invalid transition and empty actor rejected',async()=>{await assert.rejects(source.appendProgress('cases',record.id,{stage:'收件',user:'甲',comment:'x',token:record.token}),/不允許/);await assert.rejects(source.appendProgress('cases',record.id,{user:'',comment:'x',token:record.token}),/處理人/)});
await test('Case field edit appends audit event and rejects stale revision',async()=>{const old=record.token;record=await source.update('cases',record.id,{fields:{...record.fields,title:'已修正案件'},user:'主管甲',comment:'修正名稱',token:old});assert.equal(record.fields.title,'已修正案件');assert.equal(record.progress.at(-1).action,'更新欄位');await assert.rejects(source.update('cases',record.id,{fields:record.fields,user:'乙',token:old}),/其他人/)});
await test('Concurrent progress token conflict detected',async()=>{const stale=record.token;record=await source.appendProgress('cases',record.id,{user:'甲',comment:'歸檔備註',token:stale});await assert.rejects(source.appendProgress('cases',record.id,{user:'乙',comment:'舊畫面',token:stale}),/其他人/)});
await test('Unsafe IDs rejected',async()=>{await assert.rejects(source.create('contracts',{fields:{...fields,contract_id:'../outside'},user:'甲'}),/編號/)});
await test('Clause diff marks only necessary changes',()=>{assert.deepEqual(ContractReview.diff('30日內付款','60日內付款'),[{type:'delete',text:'3'},{type:'insert',text:'6'},{type:'same',text:'0日內付款'}]);assert.equal(ContractReview.diff('相同','相同').length,1)});
let review,thread;const caseDir=await(await root.getDirectoryHandle('cases')).getDirectoryHandle(record.id),versionDir=await(await caseDir.getDirectoryHandle('review',{create:true})).getDirectoryHandle('versions',{create:true});
for(const version of ['V1','V2']){const h=await versionDir.getFileHandle(version+'.md',{create:true});h.text=markdown({version_id:version,clauses:[{id:'第1條',title:'付款',text:version==='V1'?'30日內付款':'60日內付款'}]})}
await test('Read immutable review versions',async()=>{review=await source.readReview(record.id);assert.equal(review.versions.length,2);assert.equal(review.comments.length,0)});
const anchor={type:'TextQuoteSelector',exact:'60日內付款',prefix:'',suffix:''};
await test('Review creates one new comment file with actor and quote',async()=>{review=await source.appendReview(record.id,{user:'法務甲',clause_id:'第1條',version_id:'V2',expectedVersion:'V2',selector:anchor,comment:'請確認',action:'comment'});thread=review.comments[0];assert.equal(thread.user,'法務甲');assert.equal(thread.thread_id,thread.id)});
await test('Reply and resolve append without altering original',async()=>{const d=await(await caseDir.getDirectoryHandle('review')).getDirectoryHandle('comments'),old=[...d.items.values()][0].text;for(const [action,comment]of [['comment','已核對'],['resolve','']])review=await source.appendReview(record.id,{user:'需求乙',clause_id:'第1條',version_id:'V2',expectedVersion:'V2',selector:anchor,thread_id:thread.id,comment,action});assert.equal(d.items.size,3);assert.equal([...d.items.values()][0].text,old);assert.equal(ContractReview.threads(review.comments)[0].status,'已解決')});
await test('Reopen preserves discussion history',async()=>{review=await source.appendReview(record.id,{user:'法務甲',clause_id:'第1條',version_id:'V2',expectedVersion:'V2',selector:anchor,thread_id:thread.id,comment:'',action:'reopen'});assert.equal(ContractReview.threads(review.comments)[0].status,'待處理');assert.equal(review.comments.length,4)});
await test('Review rejects invalid anchor, empty actor and nonexistent thread',async()=>{const body={user:'甲',clause_id:'第1條',version_id:'V2',expectedVersion:'V2',selector:anchor,comment:'x'};await assert.rejects(source.appendReview(record.id,{...body,selector:{...anchor,exact:'不存在'}}),/錨點/);await assert.rejects(source.appendReview(record.id,{...body,user:''}),/處理人/);await assert.rejects(source.appendReview(record.id,{...body,thread_id:'missing',action:'resolve'}),/首筆/)});
await test('Review rejects stale version without creating a file',async()=>{const h=await versionDir.getFileHandle('V3.md',{create:true});h.text=markdown({version_id:'V3',clauses:[{id:'第1條',text:'新版本'}]});const d=await(await caseDir.getDirectoryHandle('review')).getDirectoryHandle('comments'),count=d.items.size;await assert.rejects(source.appendReview(record.id,{user:'甲',clause_id:'第1條',version_id:'V2',expectedVersion:'V2',selector:anchor,comment:'x'}),/版本已更新/);assert.equal(d.items.size,count)});
console.log(JSON.stringify({checks:count,failed:0}));})().catch(e=>{console.error(e);process.exitCode=1});
